### ISSUE TITLE
centOS: command not found

### ISSUE THREAD

**Issue by remyhuang03** [codedread/scour#318]
I have used pip to install the scour properly, but when I input the command, it prompted that `bash: scour: command not found`

**Comment by JoKalliauer** [comment]
There are several options:

1) Try using `python3 -m scour.scour` instead of `scour`

2) Maybe you could try using `sudo pip3 install scour` or `sudo yum install python3-pip python3-scour`

3) Maybe try seaching the executable in the subfolders of /usr and your home-folder by using `find /usr/ ~ -name scour`

4) If you know where the executable is stored, than make a symbolic link in the folder `~/bin` (or any folder in $PATH), if you prefer a grafical interface for symlinks you could use [/tassaron/symlink-editor](https://github.com/tassaron/symlink-editor).

5) Restart the computer and type `which scour`, if it returns something the comand should work.
